const MEETING_DESCRIPTION = [
  'Are you ready to take a stand and make a real difference? Your presence will help ignite the spark of change that our nation desperately needs. It\u2019s time to unselect Amy Klobuchar!',
  'Join volunteers for \u201CRoyce White for U.S. Senate\u201D as we discuss what\u2019s next! Be part of the movement that puts liberty and justice back into the hands of the people.',
  'Register to attend. Select Register and then, Add to Calendar to add the meeting series to your calendar.',
]

const MEETING_AGENDA = [
  { time: '7:00 PM', label: 'Meeting opens' },
  { time: '7:05 PM', label: 'Campaign update \u00B7 state of the race' },
  { time: '7:20 PM', label: 'Volunteer assignments \u00B7 next week\u2019s priorities' },
  { time: '7:45 PM', label: 'Q&A with the campaign team' },
  { time: '8:00 PM', label: 'Close' },
]

export const EVENTS = [
  {
    slug: 'volunteers-weekly-meeting',
    number: '01',
    title: 'Volunteers\u2019 Weekly Meeting',
    city: 'Online',
    venue: 'Zoom \u00B7 details sent after registration',
    address: 'Online meeting \u2014 link provided via email',
    date: '2026-04-22',
    dateLabel: 'APR 22 \u00B7 2026',
    day: 'Wednesday',
    timeStart: '7:00 PM',
    timeEnd: '8:00 PM',
    doors: '6:55 PM',
    tag: 'Series',
    rsvp: '/events/volunteers-weekly-meeting',
    lede: 'Are you ready to take a stand and make a real difference? Join volunteers for \u201CRoyce White for U.S. Senate\u201D as we discuss what\u2019s next.',
    description: MEETING_DESCRIPTION,
    agenda: MEETING_AGENDA,
    host: 'Royce White For Senate',
    featured: true,
  },
  {
    slug: 'volunteers-weekly-meeting-apr-29',
    number: '02',
    title: 'Volunteers\u2019 Weekly Meeting',
    city: 'Online',
    venue: 'Zoom \u00B7 details sent after registration',
    address: 'Online meeting \u2014 link provided via email',
    date: '2026-04-29',
    dateLabel: 'APR 29 \u00B7 2026',
    day: 'Wednesday',
    timeStart: '7:00 PM',
    timeEnd: '8:00 PM',
    doors: '6:55 PM',
    tag: 'Series',
    rsvp: '/events/volunteers-weekly-meeting-apr-29',
    lede: 'Weekly volunteer meeting. Learn to engage, discover effective strategies to rally your friends, family, and community behind the campaign.',
    description: MEETING_DESCRIPTION,
    agenda: MEETING_AGENDA,
    host: 'Royce White For Senate',
    featured: false,
  },
  {
    slug: 'volunteers-weekly-meeting-may-06',
    number: '03',
    title: 'Volunteers\u2019 Weekly Meeting',
    city: 'Online',
    venue: 'Zoom \u00B7 details sent after registration',
    address: 'Online meeting \u2014 link provided via email',
    date: '2026-05-06',
    dateLabel: 'MAY 06 \u00B7 2026',
    day: 'Wednesday',
    timeStart: '7:00 PM',
    timeEnd: '8:00 PM',
    doors: '6:55 PM',
    tag: 'Series',
    rsvp: '/events/volunteers-weekly-meeting-may-06',
    lede: 'Weekly volunteer meeting. Be part of the movement that puts liberty and justice back into the hands of the people.',
    description: MEETING_DESCRIPTION,
    agenda: MEETING_AGENDA,
    host: 'Royce White For Senate',
    featured: false,
  },
  {
    slug: 'volunteers-weekly-meeting-may-13',
    number: '04',
    title: 'Volunteers\u2019 Weekly Meeting',
    city: 'Online',
    venue: 'Zoom \u00B7 details sent after registration',
    address: 'Online meeting \u2014 link provided via email',
    date: '2026-05-13',
    dateLabel: 'MAY 13 \u00B7 2026',
    day: 'Wednesday',
    timeStart: '7:00 PM',
    timeEnd: '8:00 PM',
    doors: '6:55 PM',
    tag: 'Series',
    rsvp: '/events/volunteers-weekly-meeting-may-13',
    lede: 'Weekly volunteer meeting. The fight continues \u2014 and we keep showing up.',
    description: MEETING_DESCRIPTION,
    agenda: MEETING_AGENDA,
    host: 'Royce White For Senate',
    featured: false,
  },
]

export const getEventBySlug = (slug) => EVENTS.find((e) => e.slug === slug) ?? null

export const getEventSlugs = () => EVENTS.map((e) => e.slug)
