export const EVENTS = [
  {
    slug: 'rochester-town-hall',
    number: '01',
    title: 'Rochester Town Hall',
    city: 'Rochester, MN',
    venue: 'Mayo Civic Center · Hall A',
    address: '30 Civic Center Dr SE, Rochester, MN 55904',
    date: '2026-05-02',
    dateLabel: 'MAY 02 · 2026',
    day: 'Saturday',
    timeStart: '6:30 PM',
    timeEnd: '8:30 PM',
    doors: '6:00 PM',
    tag: 'Town Hall',
    rsvp: '/events/rochester-town-hall',
    lede: 'A two-hour, unfiltered town hall on the issues Olmsted County asked for — fentanyl, farm policy, and the forever wars.',
    description: [
      'Royce returns to Rochester for a no-teleprompter conversation with the communities Olmsted County elected officials have spent the last two cycles avoiding.',
      'Doors open at 6:00 PM. Prepared remarks run roughly 25 minutes. The remaining 90 minutes are yours — open mic, moderated only for time, no pre-screened questions.',
      'Bring a neighbor. Bring the hard questions. Bring someone who isn\'t yet convinced.',
    ],
    agenda: [
      { time: '6:00 PM', label: 'Doors open · coffee service' },
      { time: '6:30 PM', label: 'Remarks — "The People Are Coming"' },
      { time: '7:00 PM', label: 'Open Q&A (unmoderated)' },
      { time: '8:15 PM', label: 'Volunteer breakout · sign-up table' },
      { time: '8:30 PM', label: 'Close' },
    ],
    host: 'Olmsted County MNGOP',
    featured: true,
  },
  {
    slug: 'duluth-waterfront-rally',
    number: '02',
    title: 'Duluth Waterfront Rally',
    city: 'Duluth, MN',
    venue: 'Bayfront Festival Park',
    address: '350 Harbor Dr, Duluth, MN 55802',
    date: '2026-05-09',
    dateLabel: 'MAY 09 · 2026',
    day: 'Saturday',
    timeStart: '2:00 PM',
    timeEnd: '4:30 PM',
    doors: '1:00 PM',
    tag: 'Rally',
    rsvp: '/events/duluth-waterfront-rally',
    lede: 'Outdoor rally on the Bayfront. Bring a jacket, bring a sign, bring the family.',
    description: [
      'The campaign\'s first outdoor rally of the general season. Music, food trucks, and a short, sharp set of remarks from Royce followed by a signing line and a delegate sign-up push.',
      'Free and open to the public. No tickets required — but RSVP helps us print enough water.',
    ],
    agenda: [
      { time: '1:00 PM', label: 'Gates open · food trucks on site' },
      { time: '2:00 PM', label: 'Music set' },
      { time: '2:45 PM', label: 'Remarks from Royce' },
      { time: '3:15 PM', label: 'Signing line · delegate sign-up' },
      { time: '4:30 PM', label: 'Close' },
    ],
    host: 'St. Louis County MNGOP',
    featured: false,
  },
  {
    slug: 'st-cloud-small-business-roundtable',
    number: '03',
    title: 'St. Cloud Small Business Roundtable',
    city: 'St. Cloud, MN',
    venue: 'River\'s Edge Convention Center',
    address: '10 4th Ave S, St. Cloud, MN 56301',
    date: '2026-05-16',
    dateLabel: 'MAY 16 · 2026',
    day: 'Saturday',
    timeStart: '9:00 AM',
    timeEnd: '11:00 AM',
    doors: '8:30 AM',
    tag: 'Roundtable',
    rsvp: '/events/st-cloud-small-business-roundtable',
    lede: 'Closed-session roundtable for Central Minnesota small business owners. Coffee, record, questions, answers.',
    description: [
      'A candid two-hour session between Royce and Central Minnesota business owners on taxes, permitting, federal contracting, and the regulatory weight pulling small shops under.',
      'Seating capped at 60 — RSVP with business details to secure a seat. Press admitted to opening remarks only.',
    ],
    agenda: [
      { time: '8:30 AM', label: 'Check-in · coffee & pastries' },
      { time: '9:00 AM', label: 'Opening remarks (press admitted)' },
      { time: '9:20 AM', label: 'Roundtable (closed session)' },
      { time: '10:45 AM', label: 'One-on-one signing time' },
      { time: '11:00 AM', label: 'Close' },
    ],
    host: 'Central MN Business Alliance',
    featured: false,
  },
  {
    slug: 'brainerd-lakes-meet-and-greet',
    number: '04',
    title: 'Brainerd Lakes Meet & Greet',
    city: 'Brainerd, MN',
    venue: 'Madden\'s on Gull Lake · Town Hall',
    address: '11266 Pine Beach Peninsula, Brainerd, MN 56401',
    date: '2026-05-23',
    dateLabel: 'MAY 23 · 2026',
    day: 'Saturday',
    timeStart: '5:00 PM',
    timeEnd: '7:00 PM',
    doors: '4:30 PM',
    tag: 'Meet & Greet',
    rsvp: '/events/brainerd-lakes-meet-and-greet',
    lede: 'Casual lakeside meet and greet. Handshakes, photos, and a short Q&A — bring the kids.',
    description: [
      'Family-friendly meet and greet on the Gull Lake peninsula. Light refreshments, a short set of remarks, and plenty of time for handshakes and photos.',
      'Perfect for first-time attendees and anyone curious about the campaign who hasn\'t pulled the trigger yet.',
    ],
    agenda: [
      { time: '4:30 PM', label: 'Doors open' },
      { time: '5:00 PM', label: 'Informal mingle' },
      { time: '5:45 PM', label: 'Short remarks from Royce' },
      { time: '6:15 PM', label: 'Photos & signing line' },
      { time: '7:00 PM', label: 'Close' },
    ],
    host: 'Crow Wing County MNGOP',
    featured: false,
  },
  {
    slug: 'mankato-fundraiser-dinner',
    number: '05',
    title: 'Mankato Fundraiser Dinner',
    city: 'Mankato, MN',
    venue: 'Verizon Center · Club Room',
    address: '1 Civic Center Plaza, Mankato, MN 56001',
    date: '2026-06-06',
    dateLabel: 'JUN 06 · 2026',
    day: 'Saturday',
    timeStart: '6:00 PM',
    timeEnd: '9:00 PM',
    doors: '5:30 PM',
    tag: 'Fundraiser',
    rsvp: '/events/mankato-fundraiser-dinner',
    lede: 'Plated dinner fundraiser. Ticketed. Remarks, Q&A, photo line.',
    description: [
      'A plated, ticketed dinner benefiting the general election push. $250 / seat or $2,000 / table of eight. Corporate PAC money not accepted — individual Minnesotans only.',
      'Cocktail hour at 5:30, dinner service at 6:00, Royce takes the room at 7:30. A photo line follows dessert.',
    ],
    agenda: [
      { time: '5:30 PM', label: 'Cocktail hour · registration' },
      { time: '6:00 PM', label: 'Dinner service' },
      { time: '7:30 PM', label: 'Remarks & Q&A' },
      { time: '8:30 PM', label: 'Photo line' },
      { time: '9:00 PM', label: 'Close' },
    ],
    host: 'Royce White For Senate',
    featured: false,
  },
  {
    slug: 'bemidji-delegate-training',
    number: '06',
    title: 'Bemidji Delegate Training',
    city: 'Bemidji, MN',
    venue: 'Sanford Center · Meeting Room 2',
    address: '1111 Event Center Dr NE, Bemidji, MN 56601',
    date: '2026-06-13',
    dateLabel: 'JUN 13 · 2026',
    day: 'Saturday',
    timeStart: '10:00 AM',
    timeEnd: '12:30 PM',
    doors: '9:30 AM',
    tag: 'Training',
    rsvp: '/events/bemidji-delegate-training',
    lede: 'Delegate training for the 2026 MNGOP convention. Walk-in friendly.',
    description: [
      'If you\'ve ever wanted to be a delegate and been told it was too complicated, this session is for you. Two and a half hours, step by step, with a campaign delegate captain.',
      'No prior experience needed. No charge. Coffee on us.',
    ],
    agenda: [
      { time: '9:30 AM', label: 'Check-in' },
      { time: '10:00 AM', label: 'Session 1 — How caucuses work' },
      { time: '11:00 AM', label: 'Session 2 — Floor fight tactics' },
      { time: '12:00 PM', label: 'Q&A · sign-up table' },
      { time: '12:30 PM', label: 'Close' },
    ],
    host: 'Beltrami County MNGOP',
    featured: false,
  },
]

export const getEventBySlug = (slug) => EVENTS.find((e) => e.slug === slug) ?? null

export const getEventSlugs = () => EVENTS.map((e) => e.slug)
